name: "Bulk add"
 
on:
  push:
    branches: [ "main" ]
 
jobs:
  bulkadd:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: Get version
      id: vars
      run: echo ::set-output name=version::$(cat usernames.txt)

    - name: Test output
      run: echo ${{ steps.vars.outputs.version }}

    - name: 
      run: |
        pwd
        ls -lrt
        cat usernames.txt

    - name: 
      run: |
        for i in $(cat usernames.txt)
          do
            curl \
              -X PUT \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer  ${{ secrets.PAT }}" \
              https://api.github.com/repos/PT-DevOps/git-bulk-invite/collaborators/$i \
              -d '{"permission":"triage"}'
          done


    # - name: bulk add github users
    #   run: |
    #     curl \
    #       -X PUT \
    #       -H "Accept: application/vnd.github+json" \
    #       -H "Authorization: Bearer  ${{ secrets.PAT }}" \
    #       https://api.github.com/repos/PT-DevOps/git-bulk-invite/collaborators/Tejanarni \
    #       -d '{"permission":"triage"}'




