name: "Bulk add"
# https://docs.github.com/en/rest/collaborators/collaborators#add-a-repository-collaborator
 
on:
  push:
    branches: [ "main" ]
 
jobs:
  bulkadd:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: check files
      run: |
        pwd
        ls -lrt
        cat usernames.txt

    - name: list files
      run: |
        for i in $(cat usernames.txt)
            do
                echo $i list                 
            done

    - name: 
      run: |
        for i in $(cat usernames.txt)
            do
                curl \
                  -X PUT \
                  -H "Accept: application/vnd.github+json" \
                  -H "Authorization: Bearer  ${{ secrets.PAT }}" \
                  https://api.github.com/repos/PT-DevOps/git-bulk-invite/collaborators/$i \
                  -d '{"permission":"triage"}'
            done


    # - name: bulk add github users
    #   run: |
    #     curl \
    #       -X PUT \
    #       -H "Accept: application/vnd.github+json" \
    #       -H "Authorization: Bearer  ${{ secrets.PAT }}" \
    #       https://api.github.com/repos/PT-DevOps/git-bulk-invite/collaborators/Tejanarni \
    #       -d '{"permission":"triage"}'




