name: "Hit a webhook"
 
on:
  push:
    branches: [ "main" ]
 
jobs:
  run-updater:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: 
      run: |
        pwd
        ls -lrt
        cat usernames.txt


    - name: bulk add github users
      run: |
        curl \
          -X PUT \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer  ${{ secrets.PAT }}" \
          https://api.github.com/repos/PT-DevOps/git-bulk-invite/collaborators/Tejanarni \
          -d '{"permission":"triage"}'




